
CREATE PROC [dbo].[ShrinkDatabaseFileSize] AS

BEGIN

ALTER DATABASE FedCapCM
SET RECOVERY SIMPLE;

-- Shrink the truncated log file to 100 MB.
DBCC SHRINKFILE (FedCapCM_Log, 100);

ALTER DATABASE FedCapCM
SET RECOVERY FULL;

END
