
CREATE Proc [dbo].[UpdateBilledRetention_R2]
AS
BEGIN

DECLARE @compnayId int, @placePeriodId int,@placeId int, @periodId int, @billedStatusId int, @cmPKId int , @savedDate smalldatetime,
@period_30 int,@period_90 int,@period_180 int,@retentionIdentity int,@caseId int, @rowNumber int

--Set @compnayId = 2
--SELECT @period_30 = Enumes.EnumId FROM Enumes WHERE CompanyId = @compnayId AND Item = '30'
--SELECT @period_90 = Enumes.EnumId FROM Enumes WHERE CompanyId = @compnayId AND Item = '90'
--SELECT @period_180 = Enumes.EnumId FROM Enumes WHERE CompanyId = @compnayId AND Item = '180'
--SELECT @billedStatusId = Enumes.EnumId FROM Enumes WHERE CompanyId = @compnayId AND  (GroupId = 155) AND (Item = 'billed')

--Declare @convertList Table
--(	    ID Int 
--	   ,[CaseID] int null
--      ,[RecordID] int null
--      ,[DocType] int null
--      ,[LastUpdate] smalldatetime null
--      ,[CreateDate] smalldatetime null
--      ,[Status] int null
--      ,[Batch] int null
--      ,[AttachID] int null
--      ,[DCN] varchar(25) null
--      ,[ActionCodeID] int null
--      ,[Priority] int null
--	  ,Value int null
--)
--INSERT INTO @convertList 
 
-- SELECT * FROM OPENQuery ( ALLSECTOR,
--'With Documents AS
--(
--SELECT [ID]
--      ,[CaseID]
--      ,[RecordID]
--      ,[DocType]
--      ,[LastUpdate]
--      ,[CreateDate]
--      ,[Status]
--      ,[Batch]
--      ,[AttachID]
--      ,[DCN]
--      ,[ActionCodeID]
--      ,[Priority],
--	  ROW_Number() OVER(Partition BY Doctype , CaseID  Order By LastUpdate Desc) AS Value
--  FROM [Arborfedcap_RPT].[dbo].[cmconvertlist]
--  where DocType in (8716,8717,8718) and Status in (3,15,16)-- AND CaseId in (33, 65360,62373,65360,48 , 39081)
  
-- )
--SELECT * FROM Documents --WHERE Value = 1')
--DECLARE cursorName CURSOR -- Declare cursor
--Static FOR

--SELECT PlacementPeriodId, PlacementEntryID , PeriodId,ID,LastUpdate ,doc.CaseID,Value FROM
--(
--Select PlacementPeriodId,PlacementPeriod.PlacementEntryID,PeriodId,AvailabilityDate,ExpirationDate,
--		Case
--			When PeriodId = @period_30 then 8716
--			When PeriodId = @period_90 then 8717
--			When PeriodId = @period_180 then 8718
--			ElSE 0
--		END AS Doctype , HRACaseID
--FROM PlacementPeriod join PlacementEntry on PlacementPeriod.PlacementEntryID = PlacementEntry.PlacementEntryID
--Where CompanyId = @compnayId AND PlacementRetentionId IS NULL
--AND 
--(dateadd(day,0,datediff(day,0, PlacementEntry.FIAEntryDate)) < dateadd(day,0,datediff(day,0, '05/01/2016'))) --Stop automic billing after May 01 2016
--) AS period Join @convertList as doc on
--period.Doctype = doc.DocType AND period.HRACaseID = doc.CaseID
--AND
--( 
--		(dateadd(day,0,datediff(day,0,LastUpdate))>= dateadd(day,0,datediff(day,0, AvailabilityDate))) 
--	AND 
--		(dateadd(day,0,datediff(day,0,LastUpdate))<= dateadd(day,0,datediff(day,0, ExpirationDate))) 
--)

--order by PlacementPeriodId
--OPEN cursorName -- open the cursor

--IF @@CURSOR_ROWS > 0
--BEGIN
--	FETCH NEXT FROM cursorName INTO @placePeriodId, @placeId,@periodId,@cmPKId,@savedDate,@caseId,@rowNumber

--	WHILE @@FETCH_STATUS = 0
--	BEGIN
--		Declare @result int
--		SET @result = (Select COUNT(PlacementRetentionId) FROM PlacementRetention as retion JOIN PlacementEntry as place ON place.PlacementEntryID =																																				retion.PlacementEntryID
--						WHERE
--						RetentionId = @periodId AND RetentionStatusId = @billedStatusId
--						AND
--						HRACaseID = @caseId
--						AND
--						DATEDIFF(day, SaveAt,@savedDate) < 365)

--		If(@result = 0 OR @result is NULL)
--		Begin

--			Insert INTO [dbo].[PlacementRetention] (PlacementPeriodId, PlacementEntryID, Sequence, RetentionId, RetentionStatusId, Comment, IsBilled, DocumentId, SaveBy,													SaveAt)
--			Values(@placePeriodId,@placeId,1,@periodId,@billedStatusId,'Generated By System',1,@cmPKId,'System',@savedDate)
	
--			SET @retentionIdentity = (Select IDENT_CURRENT('PlacementRetention'))

--			Update [dbo].[PlacementPeriod] SET PlacementRetentionId = @retentionIdentity
--			Where PlacementPeriodId = @placePeriodId
--		END
--		FETCH NEXT FROM cursorName INTO @placePeriodId, @placeId,@periodId,@cmPKId,@savedDate,@caseId,@rowNumber
--	END
-- END
--CLOSE cursorName -- close the cursor
--DEALLOCATE cursorName -- Deallocate the cursor

END