CREATE TABLE [dbo].[CrS_Timekeeping_Export] (
    [Id]              INT           IDENTITY (1, 1) NOT NULL,
    [ClientID]        INT           NULL,
    [HraCaseNumber]   VARCHAR (12)  NULL,
    [Suffix]          VARCHAR (2)   NULL,
    [LineNumber]      VARCHAR (2)   NULL,
    [CIN]             VARCHAR (8)   NULL,
    [LastName]        VARCHAR (17)  NULL,
    [FirstName]       VARCHAR (10)  NULL,
    [DTSClientID]     VARCHAR (10)  NULL,
    [JobCode]         VARCHAR (8)   NULL,
    [WorkSiteCode]    VARCHAR (5)   NULL,
    [DTSAssignmentID] VARCHAR (10)  NULL,
    [AssignedHours]   INT           NULL,
    [RequiredHours]   INT           NULL,
    [ActivityDate]    DATETIME      NULL,
    [ActivityHours]   INT           NULL,
    [ActivityCodeId]  VARCHAR (8)   NULL,
    [ActivityCode]    VARCHAR (100) NULL,
    [DeleteIndicator] NCHAR (1)     NULL,
    [CycleStartDate]  DATETIME      NULL,
    [CycleEndDate]    DATETIME      NULL,
    [Status]          VARCHAR (200) NULL,
    [notes]           VARCHAR (200) NULL,
    [runId]           INT           NULL,
    [datetimestamp]   DATETIME      NULL,
    [Scheduleid]      INT           NULL
);

