CREATE TABLE [dbo].[SupportService] (
    [SupportServiceId]        INT             IDENTITY (1, 1) NOT NULL,
    [CompanyId]               INT             NULL,
    [Code]                    VARCHAR (5)     NULL,
    [Description]             VARCHAR (50)    NULL,
    [OverrideAllowed]         BIT             NULL,
    [ItemCapPeriodId]         INT             NULL,
    [ItemCapAmount]           DECIMAL (18, 2) NULL,
    [FrequencyRequired]       BIT             DEFAULT ((0)) NOT NULL,
    [ChildRequired]           BIT             DEFAULT ((0)) NOT NULL,
    [HoursRequired]           BIT             DEFAULT ((0)) NOT NULL,
    [DatesRequired]           BIT             DEFAULT ((0)) NOT NULL,
    [DescriptionRequired]     BIT             DEFAULT ((0)) NOT NULL,
    [HoursPerWeekRequired]    BIT             DEFAULT ((0)) NOT NULL,
    [WorkSiteRequired]        BIT             DEFAULT ((0)) NOT NULL,
    [ProviderTypeRequired]    BIT             DEFAULT ((0)) NOT NULL,
    [ProviderDetailsRequired] BIT             DEFAULT ((0)) NOT NULL,
    [ProviderTaxIdRequired]   BIT             DEFAULT ((0)) NOT NULL,
    [PaymentFlagRequired]     BIT             DEFAULT ((0)) NOT NULL,
    [IsEstimateRequired]      BIT             DEFAULT ((0)) NOT NULL,
    [VendorInfoRequired]      BIT             CONSTRAINT [DF_VendorInfoRequired] DEFAULT ((0)) NOT NULL,
    [IsActive]                BIT             CONSTRAINT [DF_SupportService_IsActive] DEFAULT ((1)) NOT NULL,
    [ApprovalRequired]        BIT             CONSTRAINT [DF_SupportService_ApprovalRequired] DEFAULT ((0)) NOT NULL,
    [IsDev]                   BIT             NULL,
    [IsUAT]                   BIT             NULL,
    [IsStaging]               BIT             NULL,
    [IsProd]                  BIT             NULL,
    CONSTRAINT [PK_SupportService] PRIMARY KEY CLUSTERED ([SupportServiceId] ASC)
);

