CREATE TABLE [dbo].[Historical_Change] (
    [Id]                                     INT             IDENTITY (1, 1) NOT NULL,
    [ImportDate]                             DATETIME        CONSTRAINT [DF_Historical_Change_ImportDate] DEFAULT (getdate()) NULL,
    [ClientId]                               VARCHAR (20)    NULL,
    [CaseId]                                 BIGINT          NULL,
    [SSN]                                    VARCHAR (9)     NULL,
    [ClientFirstName]                        VARCHAR (30)    NULL,
    [ClientMiddleName]                       VARCHAR (30)    NULL,
    [ClientLastName]                         VARCHAR (30)    NULL,
    [Gender]                                 VARCHAR (1)     NULL,
    [ReferringOFIOffice]                     INT             NULL,
    [BTCOffice]                              INT             NULL,
    [CaseStatus]                             VARCHAR (1)     NULL,
    [CaseStatusStartDate]                    DATETIME        NULL,
    [CaseStatusEndDate]                      DATETIME        NULL,
    [TeletypeTelephoneNumber]                VARCHAR (10)    NULL,
    [MobileTelephoneNumber]                  VARCHAR (10)    NULL,
    [MessageTelephoneNumber]                 VARCHAR (10)    NULL,
    [MessageExtension]                       VARCHAR (10)    NULL,
    [WorkTelephoneNumber]                    VARCHAR (10)    NULL,
    [WorkExtension]                          VARCHAR (10)    NULL,
    [HomeTelephoneNumber]                    VARCHAR (10)    NULL,
    [EmailAddress]                           VARCHAR (150)   NULL,
    [StreetAddress1]                         VARCHAR (50)    NULL,
    [StreetAddress2]                         VARCHAR (50)    NULL,
    [City]                                   VARCHAR (30)    NULL,
    [ZipCode]                                VARCHAR (10)    NULL,
    [MailAddress1]                           VARCHAR (50)    NULL,
    [MailAddress2]                           VARCHAR (50)    NULL,
    [MailCity]                               VARCHAR (30)    NULL,
    [MailZipCode]                            VARCHAR (10)    NULL,
    [FoodStampFamilySize]                    INT             NULL,
    [FoodStampBenefitAmount]                 DECIMAL (18, 2) NULL,
    [FoodStampBenefitMonth]                  DATETIME        NULL,
    [TANFFamilySize]                         INT             NULL,
    [TANFBenefitAmount]                      DECIMAL (18, 2) NULL,
    [TANFBenefitMonth]                       DATETIME        NULL,
    [TANFMonthsCounter]                      INT             NULL,
    [MonthsCaringForChildUnder1Exemption]    INT             NULL,
    [AlienNumber]                            VARCHAR (10)    NULL,
    [IPVHistoryCount]                        INT             NULL,
    [MarriedIndicator]                       VARCHAR (1)     NULL,
    [PrimaryLanguage]                        VARCHAR (2)     NULL,
    [PregnancyDueDate]                       DATETIME        NULL,
    [PenobscotInd]                           VARCHAR (1)     NULL,
    [LivingOnTribalLand]                     VARCHAR (1)     NULL,
    [PleasantPtPassqdyInd]                   VARCHAR (1)     NULL,
    [DanaPointPassamaquoddy]                 VARCHAR (1)     NULL,
    [HoultonMaliseet]                        VARCHAR (1)     NULL,
    [SanctionEffectiveDate]                  DATETIME        NULL,
    [SanctionStatus]                         VARCHAR (5)     NULL,
    [CaseClosureReason]                      VARCHAR (5)     NULL,
    [TANFExtensionType]                      VARCHAR (3)     NULL,
    [TANFExtensionStatus]                    VARCHAR (3)     NULL,
    [TANFExtensionDenial]                    VARCHAR (3)     NULL,
    [TANFExtensionStartDate]                 DATETIME        NULL,
    [TANFReason]                             VARCHAR (2000)  NULL,
    [TANFExtensionEndDate]                   DATETIME        NULL,
    [ChildcareSupportServiceId]              VARCHAR (1)     NULL,
    [TANFExtensionHistory]                   VARCHAR (3)     NULL,
    [CaringForDisabledFamilyMember]          VARCHAR (1)     NULL,
    [CaringForDisabledFamilyMemberStartDate] DATETIME        NULL,
    [ServiceTypeCode]                        VARCHAR (5)     NULL,
    [ServiceTypeFrequency]                   VARCHAR (10)    NULL,
    [BudgetAmount]                           DECIMAL (18, 2) NULL,
    [BudgetStartDate]                        DATETIME        NULL,
    [BudgetEndDate]                          DATETIME        NULL,
    [IncomeAmount]                           DECIMAL (18, 2) NULL,
    [IncomeStartDate]                        DATETIME        NULL,
    [IncomeVerificationType]                 VARCHAR (2)     NULL,
    [IncomeType]                             VARCHAR (5)     NULL,
    [IncomeHours]                            INT             NULL,
    [IncomePeriodType]                       VARCHAR (1)     NULL,
    [IncomeSourceType]                       VARCHAR (70)    NULL,
    [IncomeVerificationDate]                 DATETIME        NULL,
    [IncomeSourcePhoneExtension]             VARCHAR (10)    NULL,
    [IncomeSourcePhoneNumber]                VARCHAR (10)    NULL,
    [IncomeSourceContactName]                VARCHAR (50)    NULL,
    [IncomeHourlyRate]                       DECIMAL (18, 2) NULL,
    [DOB]                                    DATETIME        NULL,
    [CaringForChildUnder1]                   VARCHAR (1)     NULL,
    [CaringForChildUnder1StartDate]          DATETIME        NULL,
    [ClosureEffectiveDate]                   DATETIME        NULL,
    [ChildUnder6YrsId]                       VARCHAR (1)     NULL,
    [AspireRegCode]                          VARCHAR (5)     NULL,
    [AspireRegStartDate]                     DATETIME        NULL,
    [AspireRegEndDate]                       DATETIME        NULL,
    [FLSA]                                   INT             NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

