CREATE TABLE [dbo].[Historical_Referral] (
    [Id]                                  INT             IDENTITY (1, 1) NOT NULL,
    [ClientId]                            VARCHAR (20)    NULL,
    [CaseId]                              BIGINT          NULL,
    [SSN]                                 VARCHAR (9)     NULL,
    [ClientFirstName]                     VARCHAR (30)    NULL,
    [ClientMiddleName]                    VARCHAR (30)    NULL,
    [ClientLastName]                      VARCHAR (30)    NULL,
    [ReferralDate]                        DATETIME        NULL,
    [OrientationDate]                     DATETIME        NULL,
    [Gender]                              VARCHAR (1)     NULL,
    [ReferringOFIOffice]                  INT             NULL,
    [BTCOffice]                           INT             NULL,
    [CaseStatus]                          VARCHAR (1)     NULL,
    [CaseStatusStartDate]                 DATETIME        NULL,
    [CaseStatusEndDate]                   DATETIME        NULL,
    [TeletypeTelephoneNumber]             VARCHAR (10)    NULL,
    [MobileTelephoneNumber]               VARCHAR (10)    NULL,
    [MessageTelephoneNumber]              VARCHAR (10)    NULL,
    [MessageExtension]                    VARCHAR (10)    NULL,
    [WorkTelephoneNumber]                 VARCHAR (10)    NULL,
    [WorkExtension]                       VARCHAR (10)    NULL,
    [HomeTelephoneNumber]                 VARCHAR (10)    NULL,
    [EmailAddress]                        VARCHAR (150)   NULL,
    [PortalEmail]                         VARCHAR (150)   NULL,
    [StreetAddress1]                      VARCHAR (50)    NULL,
    [StreetAddress2]                      VARCHAR (50)    NULL,
    [City]                                VARCHAR (30)    NULL,
    [ZipCode]                             VARCHAR (10)    NULL,
    [MailAddress1]                        VARCHAR (50)    NULL,
    [MailAddress2]                        VARCHAR (50)    NULL,
    [MailCity]                            VARCHAR (30)    NULL,
    [MailZipCode]                         VARCHAR (10)    NULL,
    [ChildUnder6YrsId]                    VARCHAR (1)     NULL,
    [ChildcareSupportServiceId]           VARCHAR (1)     NULL,
    [DOB]                                 DATETIME        NULL,
    [HighestEducationLevel]               VARCHAR (2)     NULL,
    [FoodStampFamilySize]                 INT             NULL,
    [FoodStampBenefitAmount]              DECIMAL (18, 2) NULL,
    [FoodStampBenefitMonth]               DATETIME        NULL,
    [TANFFamilySize]                      INT             NULL,
    [TANFBenefitAmount]                   DECIMAL (18, 2) NULL,
    [TANFBenefitMonth]                    DATETIME        NULL,
    [TANFMonthsCounter]                   INT             NULL,
    [MonthsCaringForChildUnder1Exemption] INT             NULL,
    [AlienNumber]                         VARCHAR (10)    NULL,
    [IPVHistoryCount]                     INT             NULL,
    [MarriedIndicator]                    VARCHAR (1)     NULL,
    [TANFExtensionStatusIndicator]        VARCHAR (1)     NULL,
    [PrimaryLanguage]                     VARCHAR (2)     NULL,
    [PregnancyDueDate]                    DATETIME        NULL,
    [PenobscotInd]                        VARCHAR (1)     NULL,
    [LivingOnTribalLand]                  VARCHAR (1)     NULL,
    [PleasantPtPassqdyInd]                VARCHAR (1)     NULL,
    [DanaPointPassamaquoddy]              VARCHAR (1)     NULL,
    [AroostookMicmac]                     VARCHAR (1)     NULL,
    [HoultonMaliseet]                     VARCHAR (1)     NULL,
    [IncomeEmploymentFlag]                VARCHAR (1)     NULL,
    [Sanctioned]                          VARCHAR (1)     NULL,
    [SanctionHistoryCount]                INT             NULL,
    [FoodStampExculsion]                  INT             NULL,
    [ImportDate]                          DATETIME        CONSTRAINT [DF_Historical_Referral_ImportDate] DEFAULT (getdate()) NULL,
    [Processed]                           BIT             CONSTRAINT [DF_Historical_Referral_Processed] DEFAULT ((0)) NULL,
    [Scheduled]                           BIT             CONSTRAINT [DF_Historical_Referral_Scheduled] DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

