CREATE TABLE [dbo].[OFI_Interface_SupportService_Audit] (
    [id]                            INT            IDENTITY (1, 1) NOT NULL,
    [clientNo]                      VARCHAR (20)   NULL,
    [OFI office]                    VARCHAR (4)    NULL,
    [Service_Type_Code]             VARCHAR (5)    NULL,
    [Item_Service_Type]             VARCHAR (50)   NULL,
    [Item_CAP_amt]                  FLOAT (53)     NULL,
    [Frequency]                     VARCHAR (20)   NULL,
    [Amount]                        FLOAT (53)     NULL,
    [Child_Being_Served]            VARCHAR (200)  NULL,
    [Hours]                         INT            NULL,
    [Start_Dt]                      VARCHAR (20)   NULL,
    [END_Dt]                        VARCHAR (20)   NULL,
    [Estimate]                      VARCHAR (1)    NULL,
    [Description]                   VARCHAR (3000) NULL,
    [Work_Site]                     VARCHAR (100)  NULL,
    [Provider_Type]                 VARCHAR (200)  NULL,
    [Provider_Vendor_Name]          VARCHAR (100)  NULL,
    [Provider_Vendor_Tax_ID_Number] VARCHAR (50)   NULL,
    [Street1]                       VARCHAR (100)  NULL,
    [Street2]                       VARCHAR (100)  NULL,
    [City]                          VARCHAR (40)   NULL,
    [State]                         VARCHAR (20)   NULL,
    [Zip]                           VARCHAR (20)   NULL,
    [Payment_To_Vendor_Flag]        VARCHAR (1)    NULL,
    [Requesting Case Manager]       VARCHAR (100)  NULL,
    [FCAStart_Dt]                   VARCHAR (20)   NULL,
    [FCAEnd_Dt]                     VARCHAR (20)   NULL,
    [clientid]                      INT            NULL,
    [clientsupportserviceid]        INT            NULL,
    [datesubmitted]                 DATETIME       NULL,
    [dateadded]                     DATETIME       NULL,
    [Receipt_Invoice]               VARCHAR (1000) NULL
);

