CREATE TABLE [dbo].[WepSite] (
    [WepSiteId]            INT             IDENTITY (1, 1) NOT NULL,
    [CompanyId]            INT             NOT NULL,
    [ProviderTypeId]       INT             NULL,
    [WepDeveloperId]       INT             NULL,
    [SiteName]             VARCHAR (100)   NULL,
    [SiteStreetAddress]    VARCHAR (100)   NULL,
    [SiteCity]             VARCHAR (50)    NULL,
    [SiteState]            VARCHAR (25)    NULL,
    [SiteZipCode]          VARCHAR (20)    NULL,
    [IsAccessibleLocation] BIT             NULL,
    [HasElevator]          BIT             NULL,
    [PrimaryContact]       VARCHAR (100)   NULL,
    [PhoneNumber]          VARCHAR (20)    NULL,
    [MobileNumber]         VARCHAR (20)    NULL,
    [MobileSmsSubscribed]  BIT             NULL,
    [FaxNumber]            VARCHAR (20)    NULL,
    [FaxSubscribed]        BIT             NULL,
    [EmailAddress]         VARCHAR (50)    NULL,
    [TravelDirections]     VARCHAR (2000)  NULL,
    [OperationHourStart]   DATETIME        NULL,
    [OperationHourEnd]     DATETIME        NULL,
    [WeekendHourStart]     DATETIME        NULL,
    [WeekendHourEnd]       DATETIME        NULL,
    [Notes]                VARCHAR (2000)  NULL,
    [MouExpirationDate]    DATETIME        NULL,
    [MouSentDate]          DATETIME        NULL,
    [MouReceivedDate]      DATETIME        NULL,
    [MouSignedDate]        DATETIME        NULL,
    [SignatoryName]        VARCHAR (100)   NULL,
    [SignatoryEmail]       VARCHAR (50)    NULL,
    [CreatedBy]            VARCHAR (50)    NULL,
    [CreatedAt]            DATETIME        NULL,
    [UpdatedBy]            VARCHAR (50)    NULL,
    [UpdatedAt]            DATETIME        NULL,
    [IndustryId]           INT             NULL,
    [IsDeleted]            BIT             CONSTRAINT [DF_WepSite_IsDeleted] DEFAULT ((0)) NOT NULL,
    [WepOrganizationId]    INT             NULL,
    [MouFileBinary]        VARBINARY (MAX) NULL,
    [MouFileName]          VARCHAR (50)    NULL,
    CONSTRAINT [PK_WepSite] PRIMARY KEY CLUSTERED ([WepSiteId] ASC),
    CONSTRAINT [FK_WepSite_WepOrganization] FOREIGN KEY ([WepOrganizationId]) REFERENCES [dbo].[WepOrganization] ([WepOrganizationId])
);



